apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: outer-loop-imagesource
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: outer-loop-imagesource
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  source:
    image: harbor-repo.vmware.com/tapsme/demo:0.0.1-SNAPSHOT
